"""insert customer id in adress

Revision ID: 3c3feda87748
Revises: 0fa852924c6e
Create Date: 2022-01-14 09:34:46.793486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3feda87748'
down_revision = '0fa852924c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
