"""insert product id in product discount

Revision ID: 46ab82879f19
Revises: 3c3feda87748
Create Date: 2022-01-14 09:44:52.586750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ab82879f19'
down_revision = '3c3feda87748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
