"""add customer and address

Revision ID: 552ca8908606
Revises: 7de993c0b189
Create Date: 2022-01-12 18:05:11.468815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552ca8908606'
down_revision = '7de993c0b189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=45), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('zipcode', sa.String(length=6), nullable=True),
    sa.Column('neighbourhood', sa.String(length=45), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('phone_number', sa.String(length=45), nullable=True),
    sa.Column('genre', sa.String(length=45), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=45), nullable=True),
    sa.Column('addresses_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addresses_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    op.drop_table('address')
    # ### end Alembic commands ###
