"""add customer and address

Revision ID: af15c8eb69fe
Revises: 552ca8908606
Create Date: 2022-01-13 10:33:58.960449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af15c8eb69fe'
down_revision = '552ca8908606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
